resolver: lts-9.1
flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- QuickCheck-2.9.2
- tf-random-0.5
- random-1.1
- primitive-0.6.2.0
- scientific-0.3.5.1
- integer-logarithms-1.0.2
- text-1.2.2.2
- semigroups-0.18.3
- hashable-1.2.6.1
- unordered-containers-0.2.8.0
- tagged-0.8.5
- mtl-2.2.1
- exceptions-0.8.3
- stm-2.4.4.1
- graphviz-2999.19.0.0
- colour-2.3.3
- fgl-5.5.3.1
- polyparse-1.12
- temporary-1.2.1
- wl-pprint-text-1.1.1.0
- base-compat-0.9.1
- dlist-0.7.1.2
- multiset-0.3.3
- MonadRandom-0.5.1
